name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup JDK with Scala and SBT
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 11
      - name: Run tests with coverage
        run: sbt clean coverage squawkJVM/test coverageReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Scala.js project
        run: sbt squawkJS/fastOptJS
      - name: Move resources
        run: |
          mkdir -p gh-pages
          files=("classes/index.html" "classes/styles.css" "squawk-fastopt.js")
          for file in "${files[@]}"; do
            src="js/target/scala-3.4.2/$file"
            if [ -f "$src" ]; then
              mv "$src" gh-pages/
            else
              echo "$src not found"
                exit 1
            fi
          done
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
