name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install sbt
        uses: olafurpg/setup-scala@v14
      - name: Run tests with coverage
        run: sbt clean coverage squawkJVM/test coverageReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Scala.js project
        run: sbt squawkJS/fastOptJS
      - name: Copy resources
        run: |
          mkdir -p gh-pages
          cp js/target/scala-3.4.2/classes/index.html gh-pages/
          cp js/target/scala-3.4.2/classes/styles.css gh-pages/
          cp js/target/scala-3.4.2/squawk-fastopt.js gh-pages/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
